// Generates src/generated/*.ts from the locked JSON Schemas via
// json-schema-to-typescript. Run `npm run gen:types` to (re)write the files,
// or `npm run gen:check` to fail when the committed output drifts from the
// schema (the CI diff-gate, decision D-16).
//
// Only column_roles is generated. Two schemas are deliberately excluded:
//   - cell_record: the renderer consumes cell records as struct-of-arrays typed
//     buffers (CellBuffers), never as row objects.
//   - layout_manifest: the manifest is data the frontend *receives* over the
//     network and must validate (e.g. range-check manifest_version), so its
//     working type is the hand-written, validation-friendly mirror in
//     renderer/layout.ts — a generated type pinned to the schema literals would
//     make that validation un-writeable, and it re-duplicated ColumnRoles. The
//     schema's real enforcement for the manifest is RUNTIME validation in the
//     api-client's getManifest (issue #4), which reads the .json schema
//     directly, not a generated .ts type. See issue #5 for the D-16 reconcile.
import { compileFromFile } from "json-schema-to-typescript";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const repoRoot = resolve(pkgRoot, "..", "..");
const schemaDir = join(repoRoot, "schemas", "v2"); // in-force contract (D-33); v1/v1.1 frozen-historical
const outDir = join(pkgRoot, "src", "generated");

const bannerComment = [
  "/* eslint-disable */",
  "/**",
  " * This file was automatically generated by json-schema-to-typescript.",
  " * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,",
  ' * and run "npm run gen:types" to regenerate this file.',
  " */",
].join("\n");

const options = {
  cwd: schemaDir,
  bannerComment,
  additionalProperties: false,
  declareExternallyReferenced: true,
};

const targets = [
  { schema: "column_roles.schema.json", out: "column_roles.ts" },
];

const check = process.argv.includes("--check");

await mkdir(outDir, { recursive: true });

let drift = false;
for (const target of targets) {
  const generated = await compileFromFile(join(schemaDir, target.schema), options);
  const outPath = join(outDir, target.out);
  if (check) {
    let current = "";
    try {
      current = await readFile(outPath, "utf8");
    } catch {
      current = "";
    }
    if (current !== generated) {
      drift = true;
      console.error(`drift: ${target.out} is out of date with ${target.schema}`);
    }
  } else {
    await writeFile(outPath, generated);
    console.log(`wrote src/generated/${target.out}`);
  }
}

if (check && drift) {
  console.error("gen:check failed — run `npm run gen:types` and commit the result");
  process.exit(1);
}
